### PR TITLE
XRT-2729: Add iot_store_config_list function

### PR DESCRIPTION
**Pull request by AIM289**
Added function required for profile handling PR https://github.com/IOTechSystems/xrt/pull/1840

@SteveOss will I need to increase iot utils version here too?

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
Would factor out the generic "list stuff in a directory" into file.c, then have this used by store. Also would add support (in file) for filtering by a given optional file extension. With current code if I have a file called xx.y, I can see "strndup (dir->d_name, file_len - 5)" being problematic ...

**Comment by SteveOss** [comment]
Also missing unit test and release note update.

**Review by SteveOss — CHANGES_REQUESTED** [review]
Would have done a different split of functionality:

iot_file_list: return a list of files in a directory with a given extension (even better use regexp). The returned list should include the full file name

iot_store_config_list: Use iot_file_list and strip .json extension from file names.

OR: Could add boolean argument to iot_file_list "strip_extension"

Is a bit more of a pain to implement iot_store_config_list, but makes iot_file_list a lot more generically useful, especially if does file match with regexp.

**Comment by AIM289** [comment]
list_file() now takes in a regex string to match against files in directory. 

store_config_list() calls list_file() with a regex string for ".json", and then strips .json off the end of every file found

**Review by SteveOss — CHANGES_REQUESTED** [review]
For efficiency would replace "strlen (extension_regex) - 1" with a constant.

static const char extension_regex [] = ".json$";

Can then use sizeof (extension_regex), which is a constant (note includes string terminator)

**Review by SteveOss — CHANGES_REQUESTED** [review]
Don't the unit tests require that the test file /tmp/iot_test.json exists ?

**Comment by AIM289** [comment]
> Don't the unit tests require that the test file /tmp/iot_test.json exists ?

The file is written as part of the test_write_file test that is run just before. I know this means that the test isn't fully self contained, but the existing test_read_file test also relies on that file existing so thought it was okay?

**Review by SteveOss — APPROVED** [review]
LGTM

**Comment by AIM289** [comment]
Not sure what's going on with the branch run on jenkins. Can't seem to get it to start as it just says "disabled". The pr-merge run has passed so is it okay if you merge it without the branch run?

**Pull request merged**
