### PR TITLE
XRT-2302 feat(data): Added in iot_data_array_get function to get an element at a specific index

### PR DESCRIPTION
**Pull request by luke-shields**
Please let me know if I should back out formatting changes. I have updated my formatted to only reformat new code added for future

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
- Coding standards - need space between function name and opening brace
- Update release notes
- In general don't do a load of format changes in a PR as can't see the wood for the trees

**Comment by SteveOss** [comment]
@luke-shields Formatting changes aren't bad, but just obscure everything for the reviewer.

**Comment by luke-shields** [comment]
@SteveOss Changes made

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
