### PR TITLE
XRT-2156: Add iot_data_equal_raw function

### PR DESCRIPTION
**Pull request by amaan-akram**

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
Rather than pretty much reproduce the iot_data_equal function. Would create a new static function that is the core equality operation that takes a bool argument (raw). Then have both iot_data_equal/iot_data_equal_raw call this internal function with raw set to true/false, i.e eliminate code duplication.

**Review by SteveOss — CHANGES_REQUESTED** [review]
iot_data_equality_check does not call itself recursively e.g for collection types is explicitly calling iot_data_equal_raw, where should be calling iot_data_equality_check, so that the raw_value mode flag is applied recursively for structured data types. Also for a raw comparison an array of uint16 should compare equal to an array of uint32 if values are equal.

Suggest:

- move iot_data_compare -> iot_data_compare_check (v1, v2, raw)
- iot_data_compare implementation is iot_data_compare_check (v1, v2, false)
- iot_data_equal_raw implementation is (iot_data_compare_check (v1, v2, true) == 0)

We really want a raw variant comparison function as is more useful (e.g could support raw comparison functions for a map).

Then refactor the internal iot_data_compare_check, do deal with either raw on non raw value checking (internally will call itself recursively).

**Review by SteveOss — CHANGES_REQUESTED** [review]
Still holes in the logic:

- When comparing types that can't be cast, existing logic of type comparison should be used. Something like:

if (!raw || non_castable (v1->type, v2->type))
{
   if (v1->type != v2->type) return (v1->type < v2->type) ? -1 : 1;
 }

- Raw test for integers is probably going to fail for a large uint64_t, as the value can't be cast to an int64_t (iot_data_cast will return false if value can't be cast)

- Finally can't apply a floating point range for equality:

(if ( fabs (f1 - f2) < 0.00001) return 0;

Should be:

if (f1 == f2) return 0;

**Comment by amaan-akram** [comment]
addressed all comments apart from float comparison.

From my testing and reading absolute float comparisons generally don't work so the use of epsilon is encouraged?

After casting and trying to compare absolute values, always returns false even if values are the same  

https://www.learncpp.com/cpp-tutorial/relational-operators-and-floating-point-comparisons/#:~:text=Avoid%20using%20operator%3D%3D%20and,those%20values%20have%20been%20calculated.

**Comment by SteveOss** [comment]
Floating point values are rarely equal, that's the way it is. The comparison function still should not use an epsilon. In the devsdk we use a configurable epsilon to determine if a float value has changed, but this is set by the user.

**Comment by amaan-akram** [comment]
> Floating point values are rarely equal, that's the way it is. The comparison function still should not use an epsilon. In the devsdk we use a configurable epsilon to determine if a float value has changed, but this is set by the user.

Steve, I just tried using absolute comparisons (==)  and it fails, I can see that the devsdk's configurable epsilon is in fact working however as when I print out the values to console, they are identical and absolute e.g  `f1 = 1.23000 &  f2 = 1.23000 `  But when comparing with == it spits out false. 

Maybe the correct workaround is using the devsdk user set epsilon as the epsilon used when comparing floats? Where can I get the epsilon set by the user

**Comment by amaan-akram** [comment]
if using 
```
        if (f1 == f2)
          return 0;
        else
        {
          printf("\n f1 = %f,  f2 = %f \n", f1, f2);
          return (f1 < f2) ? -1 : 1;
        }
      }
```

get the following output 

```
  Test: data_raw_equal_different_types ...
 f1 = 1.123000,  f2 = 1.123000 

 f1 = 1.123000, f2 = 1.123000 

 f1 = 2.123000,  f2 = 1.123000 

 f1 = 1.123000, f2 = 2.123000 
FAILED
```

**Comment by amaan-akram** [comment]
@SteveOss  also, something interesting to note, If I find the difference between f1 & f2 (`f1 - f2`) and print out the result we get `-0.000000` outputted on the console

**Comment by SteveOss** [comment]
@amaan-akram In the failing == case how are f1/f2 assigned ?

**Comment by amaan-akram** [comment]
> @amaan-akram In the failing == case how are f1/f2 assigned ?

Using the following test case: 

```
  data1 = iot_data_alloc_f64 (1.123);
  data2 = iot_data_alloc_f32 (1.123f);   // have tried without "f"
  CU_ASSERT (iot_data_equal_raw (data1, data2))
```

we then cast:

```
        double_t f1;
        double_t f2;
        iot_data_cast (data1, IOT_DATA_FLOAT64, &f1);
        iot_data_cast (data2, IOT_DATA_FLOAT64, &f2);
```

and fails == check with behavior stated before

**Comment by SteveOss** [comment]
Floating point values of different types will only compare equal if the value can be represented completely in both formats (33554432 can be, 33554433 cant). So:

float f = 33554432;
double d = 33554432;
printf ("Equal 33554432: %s\n", f == d ? "true" : "false");
f = 33554433;
d = 33554433;
printf ("Equal 33554433: %s\n", f == d ? "true" : "false");

Correctly gives:

Equal 33554432: true
Equal 33554433: false

**Comment by amaan-akram** [comment]
do we not want decimal values to return true regardless of the type when comparing raw values?

E.g 
          float f = 1.123;
          double d = 1.123;
          printf (" \n Equal 1.123: %s\n", f == d ? "true" : "false");
          
          will return false 
          
          But for a raw comparison, do we not want it to return true?

**Comment by SteveOss** [comment]
float 1.23 != double 1.23 because both are different approximations of 1.23 neither is actually 1.23 exactly.

**Comment by amaan-akram** [comment]
ready for review

**Review by SteveOss — CHANGES_REQUESTED** [review]
Still want to leave original iot_data_compare function that simply maps to not_data_compare (false)

**Comment by amaan-akram** [comment]
readded iot_data_compare, as an extern function. 

Mapped it to the internal static compare function with raw set to false.

Does that sound fine? @SteveOss

**Review by SteveOss — CHANGES_REQUESTED** [review]
Oops, just spotted that raw float handling can also be normalised. Update RAW goto for floating values, then deal with by checking type in RAW section.

**Review by SteveOss — CHANGES_REQUESTED** [review]
(v1->type <= IOT_DATA_UINT64 & v2->type <= IOT_DATA_UINT64)

Here & is a bitwise not a logical AND (&&)

**Review by SteveOss — APPROVED** [review]
LGTM

**Comment by amaan-akram** [comment]
Hey Steve, can you merge this & have a look at my v1.5-branch PR, Getting some warnings on sonarcube that are unrelated to my code.

**Pull request merged**
