### PR TITLE
XRT-2623: fix for shallow map copying

### PR DESCRIPTION
**Pull request by edward-scott**

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
Yikes how did we not see this before. Can you add a unit test.

**Comment by SteveOss** [comment]
Also the new map looses any element typing (from iot_data_alloc_typed_map). So should probably create new map with iot_data_alloc_typed_map, getting both key and element type directly from source map.

**Comment by edward-scott** [comment]
I think this was not spotted because the default element type is multi and a multi key map will work in most cases. Ugh.

**Comment by SteveOss** [comment]
Need to allocate copy with iot_data_alloc_typed_map

**Review by SteveOss — APPROVED** [review]
LGTM

**Comment by edward-scott** [comment]
recheck

**Pull request merged**
