### PR TITLE
XRT-2860 fix: fix reading of json numbers to handle extreme values

### PR DESCRIPTION
**Pull request by Jwcode-uk**

### CODE REVIEW

**Comment by BinduRao2018** [comment]
@Jwcode-uk, Could you bump the version to 1.5.4 before moving for Review?

**Comment by BinduRao2018** [comment]
@SteveOss, Could you take a look at this?

**Review by SteveOss — APPROVED** [review]
LGTM

**Comment by Jwcode-uk** [comment]
@SteveOss Please can you merge as passed CI

https://jenkins.iotechsys.com/view/Components/job/IOT/view/change-requests/job/PR-335/

**Pull request merged**
