### PR TITLE
XRT-1892: performance improvements for JSON generation

### PR DESCRIPTION
**Pull request by edward-scott**

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
Although the type of size_map is correct is rather wasteful. Would make it an array of uint8_t.

**Comment by edward-scott** [comment]
Either the test is invalid or there is an issue to fix. Suggest discussing after stand up.

**Comment by edward-scott** [comment]
I think we can use a 32 byte minimum as that will be enough for int64 and uint64 and float64 with a "%.16e" format string.

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
